### ISSUE TITLE
Building stardog-graviton binary fails on OS X 

### ISSUE THREAD

**Issue by nucknorris** [stardog-union/stardog-graviton#5]
There seems to be an issue with one of the go libraries (https://github.com/fatih/color). I've set up all go-related environment variables accordingly to the README but when I try running `make` i get the following output:

```bash
$ make
./scripts/build-local.sh
# github.com/stardog-union/stardog-graviton/vendor/github.com/fatih/color
vendor/github.com/fatih/color/color.go:21: undefined: isatty.IsCygwinTerminal
make: *** [bin/stardog-graviton] Error 2
```

It looks like it's trying to call `isatty.IsCygwinTerminal`, which is only available on Windows, but not on OS X. I am using OS X 10.11.6.

**Comment by MikeSchirado** [comment]
I'm seeing the same issue on OS X 10.12.3 and Ubuntu 16.04.

**Comment by MikeSchirado** [comment]
FYI - I was able to get it to build by removing isatty.IsCygwinTerminal from vendor/github.com/fatih/color/color.go:21

`(!isatty.IsTerminal(os.Stdout.Fd()))`

**Comment by buzztroll** [comment]
@MikeSchirado  @nucknorris thanks for reporting this.  I updated the vendor dependencies and it seems to have fixed the issue.  Please let me know if this solves your problems and I will close the issue.

**Comment by nucknorris** [comment]
@buzztroll thank you for your fast response. I was able to build it now, so this issue seems to be resolved :)
