### ISSUE TITLE
Graviton does not read --config-dir option

### ISSUE THREAD

**Issue by earthquakesan** [stardog-union/stardog-graviton#67]
Expected behavior (given I have default.json in /tmp/)
```
$ ./stardog-graviton --config-dir=/tmp/
There is no base image for version 5.2.1.
Do you wish to build one? (yes/no):
...
```

Expected behavior happens when I copy default.json to default config-dir (~/.graviton/)

Actual behavior:
```
$ ./stardog-graviton --config-dir=/tmp/
What version of stardog are you launching?: 
```

I am using Graviton 1.0.6 downloaded from github releases.

**Comment by buzztroll** [comment]
The config dir option does not seem to work for default values.  Until this is fixed you can work around this by setting the env `STARDOG_VIRTUAL_APPLIANCE_CONFIG_DIR` to `/tmp` in your case.
