### ISSUE TITLE
Usability: stardog-graviton logs command

### ISSUE THREAD

**Issue by earthquakesan** [stardog-union/stardog-graviton#73]
The output of the command is as follows:
```
 % stardog-graviton logs stardog-cloud                        
Success.
```

But where are my logs? Moreover, it actually fails to collect the logs, the errors are not propagated to the user at all!

**Comment by pdmars** [comment]
You can specify the location of log output with `--output-file`, e.g. `--output-file=/tmp/stardoglogs.gz`.

And yes, you're correct that unfortunately some errors are not propagated to the user with this command. These could definitely be improved.

One thing to note: to use this command and you need to have the private SSH key used for the deployment in your keychain. If you specified a keypair at launch with `--private-key` you can simply add that same key to your keychain with `ssh-add /path/to/private/key`. If graviton created a keypair for you, you can find the private key in the deployment directory (default is `~/.graviton/deployments/<deployment name/<deployment name>key`) and add that key to your keychain.

**Comment by pdmars** [comment]
Yes, you're correct we should note where the logs are saved to when the output dir isn't specified. We'll fix that.

Log collection uses scp and gathers them from all the nodes to the bastion, and then scp's the gz file from the bastion to the system where you're running the command. It should work fine when Stardog is down.

If you added the key to the keychain and you can ssh into the bastion and then ssh to the other nodes without issue, then there's likely something else going wrong. Is there enough free space on all of the nodes for `/tmp`? Are there any errors in the graviton log for the deployment? (In `~/.graviton/<deploy>/`)
