### ISSUE TITLE
How to modify instance volume size?

### ISSUE THREAD

**Issue by earthquakesan** [stardog-union/stardog-graviton#74]
I need to load 1 billion triples in the stardog. Compressed data size is 7G (gzipped ntriples), uncompressed ~150G.

The default instance size is 16G main partition + 5G data partition. As I could see from architecture, there is no data sharding, only HA (i.e. data will be replicated over all the nodes). Then 5G is simply not enough. How can I configure volume size without changing graviton code?

**Comment by pdmars** [comment]
You can change the volume sizes with two different arguments when the deployment is launched (see `stardog-graviton launch --help`. To change this size of Stardog home you can use `--volume-size=512` (this is in gb) and you can change the size of the volume for the root partition is (where /tmp is) with `--root-volume-size=64` (also in gb). 

Depending on your data, you may also need an instance type with more memory. I'd suggest looking into the AWS memory-optimized instance types. To select a different instance type for Stardog at launch you can specify `--sd-instance-type="r4.2xlarge"` and to increase your JVM memory settings you can pass individual heap and direct memory settings via flags (see `--memory-direct`, `--memory-max`, and `--memory-start`) or all at once you can set the environment with `--env="STARDOG_JAVA_ARGS=\"-Xms24g -Xmx24g -XX:MaxDirectMemorySize=24g\""`. Note the use of escaping the quotes to ensure those values are set correctly. If they are set incorrectly you may not get an error or failed deployment, it may just start with the defaults.

**Comment by earthquakesan** [comment]
Thanks for fast reply @pdmars !

What is the /tmp partition used for?

Regarding instance size, as I understood from official benchmarking data and recommendations, 16G should be enough for 1 billion triples or?

**Comment by pdmars** [comment]
Stardog uses tmp for a number of different operations and you'll run into trouble if you run out of free space there as well as the volume used for Stardog home. You can change the location by setting `java.io.tmpdir` (e.g. if you want to move it from the root partition to the same volume used for Stardog home, which is mounted at `/mnt/data/`). To do that you'd pass it to `STARDOG_JAVA_ARGS` similar as above:

```
--env="STARDOG_JAVA_ARGS=\"-Djava.io.tmpdir=/mnt/data/ -Xms24g -Xmx24g -XX:MaxDirectMemorySize=24g\""
```

As far as the instance size, you can read more about capacity planning here: 
https://www.stardog.com/docs/#_capacity_planning

One thing to note about those values, however, is that while it is possible to start with those values it is dependent on your data. Those values are based on the BSBM benchmarking data set. However, if your data is significantly different then you may need larger instance types and memory settings than recommended in that section. It may take a bit of trial and error to find the right size for your data. Also, make sure to leave some memory free for the system as well and don't allocate everything in the instance to the JVM.

**Comment by earthquakesan** [comment]
thanks for the answers!
